/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.itson.tekz.presentacion;

import java.awt.Color;
import java.awt.Cursor;
import javax.swing.Box;
import javax.swing.JLabel;
import javax.swing.JScrollPane;





/**
 *
 * @author Cristian
 */
public class mainMenu extends javax.swing.JFrame {
boolean activate = true;


//    setCursor(hourglassCursor);

    /**
     * Creates new form mainMenu
     */
    public mainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAgregarCliente = new javax.swing.JLabel();
        lblConsultaDeConsumo = new javax.swing.JLabel();
        lblListaDeClientes = new javax.swing.JLabel();
        lblSimuladorDeLlamada = new javax.swing.JLabel();
        lblIconoAgregarCliente = new javax.swing.JLabel();
        lblIconoConsultaDeConsumo = new javax.swing.JLabel();
        lblIconoListaDeClientes = new javax.swing.JLabel();
        lblIconoSimuladorDeLlamada = new javax.swing.JLabel();
        lblLogo1 = new javax.swing.JLabel();
        lblLogo2 = new javax.swing.JLabel();
        lblFondoConsultaDeConsumo = new javax.swing.JLabel();
        lblFondoSimuladorDeLlamada = new javax.swing.JLabel();
        lblFondoListaDeClientes = new javax.swing.JLabel();
        lblFondoAgregarCliente = new javax.swing.JLabel();
        lblFondoIzquierdo = new javax.swing.JLabel();
        pnlParent = new javax.swing.JPanel();
        pnlAgregarCliente = new javax.swing.JPanel();
        lblBarraNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        lblBarraApellidos = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        txtBarraDireccion = new javax.swing.JLabel();
        lblCiudad = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox<>();
        cmbCiudad = new javax.swing.JComboBox<>();
        lblEstado = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pnlListaDeClientes = new javax.swing.JPanel();
        jLabel3ww = new javax.swing.JLabel();
        pnlConsultaDeConsumo = new javax.swing.JPanel();
        pnlSimuladorDeLlamada = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1017, 459));
        setMinimumSize(new java.awt.Dimension(1017, 459));
        setUndecorated(true);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(null);

        lblAgregarCliente.setBackground(new java.awt.Color(0, 151, 167));
        lblAgregarCliente.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        lblAgregarCliente.setForeground(new java.awt.Color(240, 240, 240));
        lblAgregarCliente.setText("Agregar cliente");
        getContentPane().add(lblAgregarCliente);
        lblAgregarCliente.setBounds(80, 140, 130, 20);

        lblConsultaDeConsumo.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        lblConsultaDeConsumo.setForeground(new java.awt.Color(255, 255, 255));
        lblConsultaDeConsumo.setText("Consulta de consumo");
        getContentPane().add(lblConsultaDeConsumo);
        lblConsultaDeConsumo.setBounds(80, 310, 180, 20);

        lblListaDeClientes.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        lblListaDeClientes.setForeground(new java.awt.Color(255, 255, 255));
        lblListaDeClientes.setText("Lista de clientes");
        getContentPane().add(lblListaDeClientes);
        lblListaDeClientes.setBounds(80, 220, 150, 20);

        lblSimuladorDeLlamada.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        lblSimuladorDeLlamada.setForeground(new java.awt.Color(255, 255, 255));
        lblSimuladorDeLlamada.setText("Simulador de llamada");
        getContentPane().add(lblSimuladorDeLlamada);
        lblSimuladorDeLlamada.setBounds(80, 400, 190, 20);

        lblIconoAgregarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/tekz/presentacion/add-friend.png"))); // NOI18N
        getContentPane().add(lblIconoAgregarCliente);
        lblIconoAgregarCliente.setBounds(40, 130, 32, 40);

        lblIconoConsultaDeConsumo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/tekz/presentacion/document.png"))); // NOI18N
        getContentPane().add(lblIconoConsultaDeConsumo);
        lblIconoConsultaDeConsumo.setBounds(40, 300, 32, 40);

        lblIconoListaDeClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/tekz/presentacion/checklist.png"))); // NOI18N
        getContentPane().add(lblIconoListaDeClientes);
        lblIconoListaDeClientes.setBounds(40, 210, 40, 40);

        lblIconoSimuladorDeLlamada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/tekz/presentacion/smartphone.png"))); // NOI18N
        getContentPane().add(lblIconoSimuladorDeLlamada);
        lblIconoSimuladorDeLlamada.setBounds(40, 390, 30, 40);

        lblLogo1.setFont(new java.awt.Font("Techno Hideo", 0, 48)); // NOI18N
        lblLogo1.setForeground(new java.awt.Color(240, 240, 240));
        lblLogo1.setText("TEKZ");
        getContentPane().add(lblLogo1);
        lblLogo1.setBounds(70, 20, 140, 40);

        lblLogo2.setFont(new java.awt.Font("Morse Tech", 0, 48)); // NOI18N
        lblLogo2.setForeground(new java.awt.Color(240, 240, 240));
        lblLogo2.setText("TEKZ");
        getContentPane().add(lblLogo2);
        lblLogo2.setBounds(120, 50, 110, 30);

        lblFondoConsultaDeConsumo.setBackground(new java.awt.Color(33, 33, 33));
        lblFondoConsultaDeConsumo.setOpaque(true);
        lblFondoConsultaDeConsumo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblFondoConsultaDeConsumoMouseMoved(evt);
            }
        });
        getContentPane().add(lblFondoConsultaDeConsumo);
        lblFondoConsultaDeConsumo.setBounds(0, 280, 290, 90);

        lblFondoSimuladorDeLlamada.setBackground(new java.awt.Color(33, 33, 33));
        lblFondoSimuladorDeLlamada.setOpaque(true);
        lblFondoSimuladorDeLlamada.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblFondoSimuladorDeLlamadaMouseMoved(evt);
            }
        });
        getContentPane().add(lblFondoSimuladorDeLlamada);
        lblFondoSimuladorDeLlamada.setBounds(0, 370, 290, 90);

        lblFondoListaDeClientes.setBackground(new java.awt.Color(33, 33, 33));
        lblFondoListaDeClientes.setOpaque(true);
        lblFondoListaDeClientes.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblFondoListaDeClientesMouseMoved(evt);
            }
        });
        getContentPane().add(lblFondoListaDeClientes);
        lblFondoListaDeClientes.setBounds(0, 190, 290, 90);

        lblFondoAgregarCliente.setBackground(new java.awt.Color(33, 33, 33));
        lblFondoAgregarCliente.setOpaque(true);
        lblFondoAgregarCliente.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblFondoAgregarClienteMouseMoved(evt);
            }
        });
        getContentPane().add(lblFondoAgregarCliente);
        lblFondoAgregarCliente.setBounds(0, 100, 290, 90);

        lblFondoIzquierdo.setBackground(new java.awt.Color(33, 33, 33));
        lblFondoIzquierdo.setOpaque(true);
        lblFondoIzquierdo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblFondoIzquierdoMouseMoved(evt);
            }
        });
        getContentPane().add(lblFondoIzquierdo);
        lblFondoIzquierdo.setBounds(0, 0, 290, 460);

        pnlParent.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlParentMouseMoved(evt);
            }
        });
        pnlParent.setLayout(new java.awt.CardLayout());

        pnlAgregarCliente.setBackground(new java.awt.Color(255, 255, 255));
        pnlAgregarCliente.setLayout(null);

        lblBarraNombre.setBackground(new java.awt.Color(153, 153, 153));
        lblBarraNombre.setOpaque(true);
        pnlAgregarCliente.add(lblBarraNombre);
        lblBarraNombre.setBounds(60, 80, 249, 1);

        txtNombre.setFont(new java.awt.Font("Microsoft Tai Le", 2, 12)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(33, 33, 33));
        txtNombre.setText("Nombre :");
        txtNombre.setBorder(null);
        txtNombre.setOpaque(false);
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreKeyPressed(evt);
            }
        });
        pnlAgregarCliente.add(txtNombre);
        txtNombre.setBounds(60, 60, 250, 20);

        txtApellidos.setFont(new java.awt.Font("Microsoft Tai Le", 2, 12)); // NOI18N
        txtApellidos.setForeground(new java.awt.Color(33, 33, 33));
        txtApellidos.setText("Apellidos :");
        txtApellidos.setBorder(null);
        txtApellidos.setOpaque(false);
        txtApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtApellidosKeyPressed(evt);
            }
        });
        pnlAgregarCliente.add(txtApellidos);
        txtApellidos.setBounds(60, 140, 250, 20);

        lblBarraApellidos.setBackground(new java.awt.Color(153, 153, 153));
        lblBarraApellidos.setOpaque(true);
        pnlAgregarCliente.add(lblBarraApellidos);
        lblBarraApellidos.setBounds(60, 160, 249, 1);

        txtDireccion.setFont(new java.awt.Font("Microsoft Tai Le", 2, 12)); // NOI18N
        txtDireccion.setForeground(new java.awt.Color(33, 33, 33));
        txtDireccion.setText("Direccion :");
        txtDireccion.setBorder(null);
        txtDireccion.setOpaque(false);
        txtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDireccionKeyPressed(evt);
            }
        });
        pnlAgregarCliente.add(txtDireccion);
        txtDireccion.setBounds(60, 220, 250, 20);

        txtBarraDireccion.setBackground(new java.awt.Color(153, 153, 153));
        txtBarraDireccion.setOpaque(true);
        pnlAgregarCliente.add(txtBarraDireccion);
        txtBarraDireccion.setBounds(60, 240, 249, 1);

        lblCiudad.setFont(new java.awt.Font("Microsoft YaHei", 2, 12)); // NOI18N
        lblCiudad.setForeground(new java.awt.Color(33, 33, 33));
        lblCiudad.setText("Ciudad :");
        pnlAgregarCliente.add(lblCiudad);
        lblCiudad.setBounds(390, 210, 50, 20);

        cmbEstado.setBorder(null);
        pnlAgregarCliente.add(cmbEstado);
        cmbEstado.setBounds(450, 140, 190, 30);

        cmbCiudad.setBorder(null);
        pnlAgregarCliente.add(cmbCiudad);
        cmbCiudad.setBounds(450, 200, 190, 30);

        lblEstado.setFont(new java.awt.Font("Microsoft YaHei", 2, 12)); // NOI18N
        lblEstado.setForeground(new java.awt.Color(33, 33, 33));
        lblEstado.setText("Estado :");
        pnlAgregarCliente.add(lblEstado);
        lblEstado.setBounds(390, 140, 50, 30);

        txtTelefono.setFont(new java.awt.Font("Microsoft Tai Le", 2, 12)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(33, 33, 33));
        txtTelefono.setText("Telefono:");
        txtTelefono.setBorder(null);
        txtTelefono.setOpaque(false);
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyPressed(evt);
            }
        });
        pnlAgregarCliente.add(txtTelefono);
        txtTelefono.setBounds(60, 310, 250, 20);

        lblTelefono.setBackground(new java.awt.Color(153, 153, 153));
        lblTelefono.setOpaque(true);
        pnlAgregarCliente.add(lblTelefono);
        lblTelefono.setBounds(60, 330, 249, 1);

        jLabel2.setFont(new java.awt.Font("Yu Gothic Light", 0, 18)); // NOI18N
        jLabel2.setText("Aceptar");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.setFocusable(false);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlAgregarCliente.add(jLabel2);
        jLabel2.setBounds(330, 410, 60, 30);

        jLabel1.setBackground(new java.awt.Color(0, 188, 212));
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.setOpaque(true);
        pnlAgregarCliente.add(jLabel1);
        jLabel1.setBounds(30, 410, 690, 30);

        pnlParent.add(pnlAgregarCliente, "card3");

        pnlListaDeClientes.setBackground(new java.awt.Color(255, 255, 255));
        pnlListaDeClientes.setLayout(new javax.swing.BoxLayout(pnlListaDeClientes, javax.swing.BoxLayout.Y_AXIS));

        jLabel3ww.setText("jLabel3");
        pnlListaDeClientes.add(jLabel3ww);

        pnlParent.add(pnlListaDeClientes, "card4");

        javax.swing.GroupLayout pnlConsultaDeConsumoLayout = new javax.swing.GroupLayout(pnlConsultaDeConsumo);
        pnlConsultaDeConsumo.setLayout(pnlConsultaDeConsumoLayout);
        pnlConsultaDeConsumoLayout.setHorizontalGroup(
            pnlConsultaDeConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );
        pnlConsultaDeConsumoLayout.setVerticalGroup(
            pnlConsultaDeConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        pnlParent.add(pnlConsultaDeConsumo, "card5");

        javax.swing.GroupLayout pnlSimuladorDeLlamadaLayout = new javax.swing.GroupLayout(pnlSimuladorDeLlamada);
        pnlSimuladorDeLlamada.setLayout(pnlSimuladorDeLlamadaLayout);
        pnlSimuladorDeLlamadaLayout.setHorizontalGroup(
            pnlSimuladorDeLlamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );
        pnlSimuladorDeLlamadaLayout.setVerticalGroup(
            pnlSimuladorDeLlamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        pnlParent.add(pnlSimuladorDeLlamada, "card2");

        getContentPane().add(pnlParent);
        pnlParent.setBounds(290, 0, 730, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
     
            

    }//GEN-LAST:event_formMouseClicked

    private void txtNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyPressed


    }//GEN-LAST:event_txtNombreKeyPressed

    private void txtApellidosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidosKeyPressed
   
    }//GEN-LAST:event_txtApellidosKeyPressed

    private void txtDireccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionKeyPressed

    private void lblFondoConsultaDeConsumoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFondoConsultaDeConsumoMouseMoved
     
        lblFondoConsultaDeConsumo.setCursor(new Cursor (Cursor.HAND_CURSOR));
        lblIconoConsultaDeConsumo.setCursor(new Cursor (Cursor.HAND_CURSOR));
        lblConsultaDeConsumo.setCursor(new Cursor (Cursor.HAND_CURSOR));
        lblFondoConsultaDeConsumo.setBackground(new Color (66,66,66));	
        lblFondoListaDeClientes.setBackground(new Color (33,33,33));	
        lblFondoAgregarCliente.setBackground(new Color (33,33,33));
        lblFondoSimuladorDeLlamada.setBackground(new Color (33,33,33));
       this.repaint();
       this.revalidate();
       
    }//GEN-LAST:event_lblFondoConsultaDeConsumoMouseMoved

    private void lblFondoSimuladorDeLlamadaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFondoSimuladorDeLlamadaMouseMoved
        lblFondoSimuladorDeLlamada.setCursor(new Cursor (Cursor.HAND_CURSOR));
         lblIconoSimuladorDeLlamada.setCursor(new Cursor (Cursor.HAND_CURSOR));
        lblSimuladorDeLlamada.setCursor(new Cursor (Cursor.HAND_CURSOR));
        lblFondoSimuladorDeLlamada.setBackground(new Color (66,66,66));
        lblFondoListaDeClientes.setBackground(new Color (33,33,33));	
        lblFondoConsultaDeConsumo.setBackground(new Color (33,33,33));
        lblFondoAgregarCliente.setBackground(new Color (33,33,33));
         this.repaint();
       this.revalidate();
    }//GEN-LAST:event_lblFondoSimuladorDeLlamadaMouseMoved

    private void pnlParentMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlParentMouseMoved
         lblFondoSimuladorDeLlamada.setBackground(new Color (33,33,33));	
        lblFondoConsultaDeConsumo.setBackground(new Color (33,33,33));
        lblFondoAgregarCliente.setBackground(new Color (33,33,33));  
                lblFondoListaDeClientes.setBackground(new Color (33,33,33));		
   this.repaint();
       this.revalidate();
    }//GEN-LAST:event_pnlParentMouseMoved

    private void lblFondoListaDeClientesMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFondoListaDeClientesMouseMoved
        lblFondoListaDeClientes.setCursor(new Cursor (Cursor.HAND_CURSOR));
        lblIconoListaDeClientes.setCursor(new Cursor (Cursor.HAND_CURSOR));
        lblListaDeClientes.setCursor(new Cursor (Cursor.HAND_CURSOR));
        lblFondoListaDeClientes.setBackground(new Color (66,66,66));
        lblFondoSimuladorDeLlamada.setBackground(new Color (33,33,33));	
        lblFondoConsultaDeConsumo.setBackground(new Color (33,33,33));
        lblFondoAgregarCliente.setBackground(new Color (33,33,33));
         this.repaint();
       this.revalidate();
    }//GEN-LAST:event_lblFondoListaDeClientesMouseMoved

    private void lblFondoAgregarClienteMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFondoAgregarClienteMouseMoved
         lblFondoAgregarCliente.setCursor(new Cursor (Cursor.HAND_CURSOR));
         lblIconoAgregarCliente.setCursor(new Cursor (Cursor.HAND_CURSOR));
        lblAgregarCliente.setCursor(new Cursor (Cursor.HAND_CURSOR));
        lblFondoAgregarCliente.setBackground(new Color (66,66,66));
        lblFondoListaDeClientes.setBackground(new Color (33,33,33));	
        lblFondoConsultaDeConsumo.setBackground(new Color (33,33,33));
        lblFondoSimuladorDeLlamada.setBackground(new Color (33,33,33));
         this.repaint();
       this.revalidate();
    }//GEN-LAST:event_lblFondoAgregarClienteMouseMoved

    private void lblFondoIzquierdoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFondoIzquierdoMouseMoved
   lblFondoSimuladorDeLlamada.setBackground(new Color (33,33,33));	
        lblFondoConsultaDeConsumo.setBackground(new Color (33,33,33));
        lblFondoAgregarCliente.setBackground(new Color (33,33,33));  
                lblFondoListaDeClientes.setBackground(new Color (33,33,33));	
   this.repaint();
       this.revalidate();
    }//GEN-LAST:event_lblFondoIzquierdoMouseMoved

    private void txtTelefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainMenu().setVisible(true);
            }
        });
    }
    
  //  public void Agregar(){
             //  jPanel3.add(pane11, "1");
           //  / / jPanel3.add(pane22,"2");

   // }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbCiudad;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3ww;
    private javax.swing.JLabel lblAgregarCliente;
    private javax.swing.JLabel lblBarraApellidos;
    private javax.swing.JLabel lblBarraNombre;
    private javax.swing.JLabel lblCiudad;
    private javax.swing.JLabel lblConsultaDeConsumo;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFondoAgregarCliente;
    private javax.swing.JLabel lblFondoConsultaDeConsumo;
    private javax.swing.JLabel lblFondoIzquierdo;
    private javax.swing.JLabel lblFondoListaDeClientes;
    private javax.swing.JLabel lblFondoSimuladorDeLlamada;
    private javax.swing.JLabel lblIconoAgregarCliente;
    private javax.swing.JLabel lblIconoConsultaDeConsumo;
    private javax.swing.JLabel lblIconoListaDeClientes;
    private javax.swing.JLabel lblIconoSimuladorDeLlamada;
    private javax.swing.JLabel lblListaDeClientes;
    private javax.swing.JLabel lblLogo1;
    private javax.swing.JLabel lblLogo2;
    private javax.swing.JLabel lblSimuladorDeLlamada;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JPanel pnlAgregarCliente;
    private javax.swing.JPanel pnlConsultaDeConsumo;
    private javax.swing.JPanel pnlListaDeClientes;
    private javax.swing.JPanel pnlParent;
    private javax.swing.JPanel pnlSimuladorDeLlamada;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JLabel txtBarraDireccion;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
