/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.itson.tekz.presentacion;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableCellRenderer;
import mx.itson.tekz.implementacion.operacionUsuario;





/**
 *
 * @author Cristian
 */
public class mainMenu extends javax.swing.JFrame {
boolean activate = true;
operacionUsuario opu = new operacionUsuario();


    /**
     * Creates new form mainMenu
     */
    public mainMenu() {
        initComponents();
        Cargar();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAgregarCliente = new javax.swing.JLabel();
        lblConsultaDeConsumo = new javax.swing.JLabel();
        lblListaDeClientes = new javax.swing.JLabel();
        lblSimuladorDeLlamada = new javax.swing.JLabel();
        lblIconoAgregarCliente = new javax.swing.JLabel();
        lblIconoConsultaDeConsumo = new javax.swing.JLabel();
        lblIconoListaDeClientes = new javax.swing.JLabel();
        lblIconoSimuladorDeLlamada = new javax.swing.JLabel();
        lblFondoConsultaDeConsumo = new javax.swing.JLabel();
        lblFondoSimuladorDeLlamada = new javax.swing.JLabel();
        lblFondoListaDeClientes = new javax.swing.JLabel();
        lblFondoAgregarCliente = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblFondoIzquierdo = new javax.swing.JLabel();
        pnlParent = new javax.swing.JPanel();
        pnlAgregarCliente = new javax.swing.JPanel();
        lblBarraNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        lblBarraApellidos = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        txtBarraDireccion = new javax.swing.JLabel();
        lblCiudad = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox<>();
        cmbCiudad = new javax.swing.JComboBox<>();
        lblEstado = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        lblAceptar = new javax.swing.JLabel();
        lblFondoAceptar = new javax.swing.JLabel();
        lblTelefonoOculto = new javax.swing.JLabel();
        lblNombreOculto = new javax.swing.JLabel();
        lblApellidosOculto = new javax.swing.JLabel();
        lblDireccionOculto = new javax.swing.JLabel();
        pnlListaDeClientes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        lblEliminar = new javax.swing.JLabel();
        lblEditar = new javax.swing.JLabel();
        lblVerCliente = new javax.swing.JLabel();
        lblFondoVerCliente = new javax.swing.JLabel();
        lblFondoEliminar = new javax.swing.JLabel();
        lblFondoEditar = new javax.swing.JLabel();
        pnlConsultaDeConsumo = new javax.swing.JPanel();
        txtNumeroDeCuenta = new javax.swing.JTextField();
        lblBarraNumeroDeCuenta = new javax.swing.JLabel();
        cmbMes = new javax.swing.JComboBox<>();
        lblMes = new javax.swing.JLabel();
        lblAño = new javax.swing.JLabel();
        cmbAño = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pnlSimuladorDeLlamada = new javax.swing.JPanel();
        lblDuracion = new javax.swing.JLabel();
        sdrDuracion = new javax.swing.JSlider();
        txtNumeroALlamar = new javax.swing.JTextField();
        lblMin = new javax.swing.JLabel();
        lblMesSDL = new javax.swing.JLabel();
        lblAñoSDL = new javax.swing.JLabel();
        cmbMesSDL = new javax.swing.JComboBox<>();
        cmbDia = new javax.swing.JComboBox<>();
        cmdAñoSDL = new javax.swing.JComboBox<>();
        lblBarraNumeroALlamar = new javax.swing.JLabel();
        lblDia = new javax.swing.JLabel();
        cmbHora = new javax.swing.JComboBox<>();
        lblHora = new javax.swing.JLabel();
        cmbMin = new javax.swing.JComboBox<>();
        lblAceptarSDL = new javax.swing.JLabel();
        lblFondoAceptarSDL = new javax.swing.JLabel();
        lblAutoGenerarLlamada = new javax.swing.JLabel();
        lblFondoAutoGenerarLlamada = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        lbl6 = new javax.swing.JLabel();
        lbl7 = new javax.swing.JLabel();
        lbl8 = new javax.swing.JLabel();
        lbl9 = new javax.swing.JLabel();
        lbl0 = new javax.swing.JLabel();
        lblFondo2 = new javax.swing.JLabel();
        lblFondo3 = new javax.swing.JLabel();
        lblFondo4 = new javax.swing.JLabel();
        lblFondo5 = new javax.swing.JLabel();
        lblFondo6 = new javax.swing.JLabel();
        lblFondo7 = new javax.swing.JLabel();
        lblFondo8 = new javax.swing.JLabel();
        lblFondo9 = new javax.swing.JLabel();
        lblFondo0 = new javax.swing.JLabel();
        lblFondo1 = new javax.swing.JLabel();
        lblNoLlamarOculto = new javax.swing.JLabel();
        lblNoCuentaOculto = new javax.swing.JLabel();
        lblBarraNumeroALlamar1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        lblCuenta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1017, 459));
        setUndecorated(true);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(null);

        lblAgregarCliente.setBackground(new java.awt.Color(0, 151, 167));
        lblAgregarCliente.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        lblAgregarCliente.setForeground(new java.awt.Color(240, 240, 240));
        lblAgregarCliente.setText("Agregar cliente");
        lblAgregarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAgregarClienteMouseClicked(evt);
            }
        });
        getContentPane().add(lblAgregarCliente);
        lblAgregarCliente.setBounds(80, 140, 130, 20);

        lblConsultaDeConsumo.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        lblConsultaDeConsumo.setForeground(new java.awt.Color(255, 255, 255));
        lblConsultaDeConsumo.setText("Consulta de consumo");
        lblConsultaDeConsumo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblConsultaDeConsumoMouseClicked(evt);
            }
        });
        getContentPane().add(lblConsultaDeConsumo);
        lblConsultaDeConsumo.setBounds(80, 310, 180, 20);

        lblListaDeClientes.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        lblListaDeClientes.setForeground(new java.awt.Color(255, 255, 255));
        lblListaDeClientes.setText("Lista de clientes");
        lblListaDeClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblListaDeClientesMouseClicked(evt);
            }
        });
        getContentPane().add(lblListaDeClientes);
        lblListaDeClientes.setBounds(80, 220, 150, 20);

        lblSimuladorDeLlamada.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        lblSimuladorDeLlamada.setForeground(new java.awt.Color(255, 255, 255));
        lblSimuladorDeLlamada.setText("Simulador de llamada");
        lblSimuladorDeLlamada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSimuladorDeLlamadaMouseClicked(evt);
            }
        });
        getContentPane().add(lblSimuladorDeLlamada);
        lblSimuladorDeLlamada.setBounds(80, 400, 190, 20);

        lblIconoAgregarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/tekz/presentacion/add-friend.png"))); // NOI18N
        lblIconoAgregarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconoAgregarClienteMouseClicked(evt);
            }
        });
        getContentPane().add(lblIconoAgregarCliente);
        lblIconoAgregarCliente.setBounds(40, 130, 32, 40);

        lblIconoConsultaDeConsumo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/tekz/presentacion/document.png"))); // NOI18N
        lblIconoConsultaDeConsumo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconoConsultaDeConsumoMouseClicked(evt);
            }
        });
        getContentPane().add(lblIconoConsultaDeConsumo);
        lblIconoConsultaDeConsumo.setBounds(40, 300, 32, 40);

        lblIconoListaDeClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/tekz/presentacion/checklist.png"))); // NOI18N
        lblIconoListaDeClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconoListaDeClientesMouseClicked(evt);
            }
        });
        getContentPane().add(lblIconoListaDeClientes);
        lblIconoListaDeClientes.setBounds(40, 210, 40, 40);

        lblIconoSimuladorDeLlamada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/tekz/presentacion/smartphone.png"))); // NOI18N
        lblIconoSimuladorDeLlamada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconoSimuladorDeLlamadaMouseClicked(evt);
            }
        });
        getContentPane().add(lblIconoSimuladorDeLlamada);
        lblIconoSimuladorDeLlamada.setBounds(40, 390, 30, 40);

        lblFondoConsultaDeConsumo.setBackground(new java.awt.Color(33, 33, 33));
        lblFondoConsultaDeConsumo.setOpaque(true);
        lblFondoConsultaDeConsumo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblFondoConsultaDeConsumoMouseMoved(evt);
            }
        });
        lblFondoConsultaDeConsumo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFondoConsultaDeConsumoMouseClicked(evt);
            }
        });
        getContentPane().add(lblFondoConsultaDeConsumo);
        lblFondoConsultaDeConsumo.setBounds(0, 280, 290, 90);

        lblFondoSimuladorDeLlamada.setBackground(new java.awt.Color(33, 33, 33));
        lblFondoSimuladorDeLlamada.setOpaque(true);
        lblFondoSimuladorDeLlamada.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblFondoSimuladorDeLlamadaMouseMoved(evt);
            }
        });
        lblFondoSimuladorDeLlamada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFondoSimuladorDeLlamadaMouseClicked(evt);
            }
        });
        getContentPane().add(lblFondoSimuladorDeLlamada);
        lblFondoSimuladorDeLlamada.setBounds(0, 370, 290, 90);

        lblFondoListaDeClientes.setBackground(new java.awt.Color(33, 33, 33));
        lblFondoListaDeClientes.setOpaque(true);
        lblFondoListaDeClientes.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblFondoListaDeClientesMouseMoved(evt);
            }
        });
        lblFondoListaDeClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFondoListaDeClientesMouseClicked(evt);
            }
        });
        getContentPane().add(lblFondoListaDeClientes);
        lblFondoListaDeClientes.setBounds(0, 190, 290, 90);

        lblFondoAgregarCliente.setBackground(new java.awt.Color(33, 33, 33));
        lblFondoAgregarCliente.setOpaque(true);
        lblFondoAgregarCliente.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblFondoAgregarClienteMouseMoved(evt);
            }
        });
        lblFondoAgregarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFondoAgregarClienteMouseClicked(evt);
            }
        });
        getContentPane().add(lblFondoAgregarCliente);
        lblFondoAgregarCliente.setBounds(0, 100, 290, 90);

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/tekz/presentacion/logo.png"))); // NOI18N
        getContentPane().add(lblLogo);
        lblLogo.setBounds(70, 20, 166, 80);

        lblFondoIzquierdo.setBackground(new java.awt.Color(33, 33, 33));
        lblFondoIzquierdo.setOpaque(true);
        lblFondoIzquierdo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblFondoIzquierdoMouseMoved(evt);
            }
        });
        getContentPane().add(lblFondoIzquierdo);
        lblFondoIzquierdo.setBounds(0, 0, 290, 460);

        pnlParent.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlParentMouseMoved(evt);
            }
        });
        pnlParent.setLayout(new java.awt.CardLayout());

        pnlAgregarCliente.setBackground(new java.awt.Color(51, 51, 51));
        pnlAgregarCliente.setLayout(null);

        lblBarraNombre.setBackground(new java.awt.Color(153, 153, 153));
        lblBarraNombre.setOpaque(true);
        pnlAgregarCliente.add(lblBarraNombre);
        lblBarraNombre.setBounds(60, 80, 249, 1);

        txtNombre.setBackground(new java.awt.Color(51, 51, 51));
        txtNombre.setFont(new java.awt.Font("Microsoft Tai Le", 2, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre.setOpaque(false);
        pnlAgregarCliente.add(txtNombre);
        txtNombre.setBounds(60, 60, 250, 20);

        txtApellidos.setBackground(new java.awt.Color(51, 51, 51));
        txtApellidos.setFont(new java.awt.Font("Microsoft Tai Le", 2, 14)); // NOI18N
        txtApellidos.setForeground(new java.awt.Color(255, 255, 255));
        txtApellidos.setOpaque(false);
        pnlAgregarCliente.add(txtApellidos);
        txtApellidos.setBounds(60, 140, 250, 20);

        lblBarraApellidos.setBackground(new java.awt.Color(153, 153, 153));
        lblBarraApellidos.setOpaque(true);
        pnlAgregarCliente.add(lblBarraApellidos);
        lblBarraApellidos.setBounds(60, 160, 249, 1);

        txtDireccion.setBackground(new java.awt.Color(51, 51, 51));
        txtDireccion.setFont(new java.awt.Font("Microsoft Tai Le", 2, 14)); // NOI18N
        txtDireccion.setForeground(new java.awt.Color(255, 255, 255));
        txtDireccion.setOpaque(false);
        pnlAgregarCliente.add(txtDireccion);
        txtDireccion.setBounds(60, 220, 250, 20);

        txtBarraDireccion.setBackground(new java.awt.Color(153, 153, 153));
        txtBarraDireccion.setOpaque(true);
        pnlAgregarCliente.add(txtBarraDireccion);
        txtBarraDireccion.setBounds(60, 240, 249, 1);

        lblCiudad.setFont(new java.awt.Font("Microsoft YaHei", 2, 14)); // NOI18N
        lblCiudad.setForeground(new java.awt.Color(255, 255, 255));
        lblCiudad.setText("Ciudad :");
        pnlAgregarCliente.add(lblCiudad);
        lblCiudad.setBounds(370, 210, 60, 20);

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aguascalientes", "Baja California", "Baja California Sur", "Campeche", "Chiapas", "Chihuahua", "Ciudad de Mexico", "Coahuila", "Colima", "Durango", "Guanajuato", "Guerrero", "Hidalgo", "Jalisco", "Mexico", "Michoacan", "Morelos", "Nayarit", "Nuevo Leon", "Oaxaca", "Puebla", "Queretaro", "Quintana Roo", "San Luis Potosi", "Sinaloa", "Sonora", "Tabasco", "Tamaulipas", "Tlaxcala", "Veracruz", "Yucatan", "Zacatecas" }));
        cmbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEstadoActionPerformed(evt);
            }
        });
        pnlAgregarCliente.add(cmbEstado);
        cmbEstado.setBounds(450, 140, 190, 30);

        pnlAgregarCliente.add(cmbCiudad);
        cmbCiudad.setBounds(450, 200, 190, 30);

        lblEstado.setFont(new java.awt.Font("Microsoft YaHei", 2, 14)); // NOI18N
        lblEstado.setForeground(new java.awt.Color(255, 255, 255));
        lblEstado.setText("Estado :");
        pnlAgregarCliente.add(lblEstado);
        lblEstado.setBounds(370, 140, 60, 30);

        txtTelefono.setBackground(new java.awt.Color(51, 51, 51));
        txtTelefono.setFont(new java.awt.Font("Microsoft Tai Le", 2, 14)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(255, 255, 255));
        txtTelefono.setOpaque(false);
        pnlAgregarCliente.add(txtTelefono);
        txtTelefono.setBounds(60, 310, 250, 20);

        lblTelefono.setBackground(new java.awt.Color(153, 153, 153));
        lblTelefono.setOpaque(true);
        pnlAgregarCliente.add(lblTelefono);
        lblTelefono.setBounds(60, 330, 249, 1);

        lblAceptar.setFont(new java.awt.Font("Yu Gothic Light", 0, 18)); // NOI18N
        lblAceptar.setText("Aceptar");
        lblAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblAceptar.setFocusable(false);
        lblAceptar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlAgregarCliente.add(lblAceptar);
        lblAceptar.setBounds(330, 410, 60, 30);

        lblFondoAceptar.setBackground(new java.awt.Color(0, 188, 212));
        lblFondoAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblFondoAceptar.setOpaque(true);
        lblFondoAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFondoAceptarMouseClicked(evt);
            }
        });
        pnlAgregarCliente.add(lblFondoAceptar);
        lblFondoAceptar.setBounds(30, 410, 690, 30);

        lblTelefonoOculto.setFont(new java.awt.Font("Microsoft Tai Le", 2, 16)); // NOI18N
        lblTelefonoOculto.setForeground(new java.awt.Color(255, 255, 255));
        lblTelefonoOculto.setText("Teléfono :");
        pnlAgregarCliente.add(lblTelefonoOculto);
        lblTelefonoOculto.setBounds(60, 290, 80, 18);

        lblNombreOculto.setFont(new java.awt.Font("Microsoft Tai Le", 2, 16)); // NOI18N
        lblNombreOculto.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreOculto.setText("Nombre :");
        pnlAgregarCliente.add(lblNombreOculto);
        lblNombreOculto.setBounds(60, 40, 80, 21);

        lblApellidosOculto.setFont(new java.awt.Font("Microsoft Tai Le", 2, 16)); // NOI18N
        lblApellidosOculto.setForeground(new java.awt.Color(255, 255, 255));
        lblApellidosOculto.setText("Apellidos :");
        pnlAgregarCliente.add(lblApellidosOculto);
        lblApellidosOculto.setBounds(60, 120, 80, 18);

        lblDireccionOculto.setFont(new java.awt.Font("Microsoft Tai Le", 2, 16)); // NOI18N
        lblDireccionOculto.setForeground(new java.awt.Color(255, 255, 255));
        lblDireccionOculto.setText("Dirección :");
        pnlAgregarCliente.add(lblDireccionOculto);
        lblDireccionOculto.setBounds(60, 200, 80, 18);

        pnlParent.add(pnlAgregarCliente, "card3");

        pnlListaDeClientes.setBackground(new java.awt.Color(51, 51, 51));
        pnlListaDeClientes.setLayout(null);

        jScrollPane1.setBackground(new java.awt.Color(51, 51, 51));

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellidos", "Telefono", "Direccion", "Ciudad", "Estado", "Cuenta"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblClientes.setToolTipText("");
        tblClientes.setOpaque(false);
        jScrollPane1.setViewportView(tblClientes);

        pnlListaDeClientes.add(jScrollPane1);
        jScrollPane1.setBounds(10, 11, 710, 370);

        lblEliminar.setFont(new java.awt.Font("Yu Gothic Light", 0, 18)); // NOI18N
        lblEliminar.setText("Eliminar");
        lblEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlListaDeClientes.add(lblEliminar);
        lblEliminar.setBounds(90, 410, 70, 30);

        lblEditar.setFont(new java.awt.Font("Yu Gothic Light", 0, 18)); // NOI18N
        lblEditar.setText("Editar");
        lblEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlListaDeClientes.add(lblEditar);
        lblEditar.setBounds(350, 410, 60, 30);

        lblVerCliente.setFont(new java.awt.Font("Yu Gothic Light", 0, 18)); // NOI18N
        lblVerCliente.setText("Ver cliente");
        lblVerCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlListaDeClientes.add(lblVerCliente);
        lblVerCliente.setBounds(580, 410, 90, 30);

        lblFondoVerCliente.setBackground(new java.awt.Color(0, 188, 212));
        lblFondoVerCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblFondoVerCliente.setMaximumSize(new java.awt.Dimension(10, 10));
        lblFondoVerCliente.setMinimumSize(new java.awt.Dimension(10, 10));
        lblFondoVerCliente.setOpaque(true);
        lblFondoVerCliente.setPreferredSize(new java.awt.Dimension(10, 10));
        pnlListaDeClientes.add(lblFondoVerCliente);
        lblFondoVerCliente.setBounds(520, 410, 200, 32);

        lblFondoEliminar.setBackground(new java.awt.Color(0, 188, 212));
        lblFondoEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblFondoEliminar.setMaximumSize(new java.awt.Dimension(10, 10));
        lblFondoEliminar.setMinimumSize(new java.awt.Dimension(10, 10));
        lblFondoEliminar.setOpaque(true);
        lblFondoEliminar.setPreferredSize(new java.awt.Dimension(10, 10));
        pnlListaDeClientes.add(lblFondoEliminar);
        lblFondoEliminar.setBounds(20, 410, 200, 32);

        lblFondoEditar.setBackground(new java.awt.Color(0, 188, 212));
        lblFondoEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblFondoEditar.setMaximumSize(new java.awt.Dimension(10, 10));
        lblFondoEditar.setMinimumSize(new java.awt.Dimension(10, 10));
        lblFondoEditar.setOpaque(true);
        lblFondoEditar.setPreferredSize(new java.awt.Dimension(10, 10));
        pnlListaDeClientes.add(lblFondoEditar);
        lblFondoEditar.setBounds(270, 410, 200, 32);

        pnlParent.add(pnlListaDeClientes, "card4");

        pnlConsultaDeConsumo.setBackground(new java.awt.Color(51, 51, 51));
        pnlConsultaDeConsumo.setLayout(null);

        txtNumeroDeCuenta.setBackground(new java.awt.Color(51, 51, 51));
        txtNumeroDeCuenta.setFont(new java.awt.Font("Microsoft Tai Le", 2, 12)); // NOI18N
        txtNumeroDeCuenta.setForeground(new java.awt.Color(255, 255, 255));
        txtNumeroDeCuenta.setText("Numero de cuenta :");
        txtNumeroDeCuenta.setToolTipText("");
        pnlConsultaDeConsumo.add(txtNumeroDeCuenta);
        txtNumeroDeCuenta.setBounds(30, 30, 230, 20);

        lblBarraNumeroDeCuenta.setBackground(new java.awt.Color(153, 153, 153));
        lblBarraNumeroDeCuenta.setMaximumSize(new java.awt.Dimension(34, 1));
        lblBarraNumeroDeCuenta.setMinimumSize(new java.awt.Dimension(34, 1));
        lblBarraNumeroDeCuenta.setOpaque(true);
        lblBarraNumeroDeCuenta.setPreferredSize(new java.awt.Dimension(34, 1));
        lblBarraNumeroDeCuenta.setRequestFocusEnabled(false);
        pnlConsultaDeConsumo.add(lblBarraNumeroDeCuenta);
        lblBarraNumeroDeCuenta.setBounds(30, 50, 250, 1);

        cmbMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMesActionPerformed(evt);
            }
        });
        pnlConsultaDeConsumo.add(cmbMes);
        cmbMes.setBounds(350, 30, 100, 30);

        lblMes.setFont(new java.awt.Font("Microsoft Tai Le", 2, 12)); // NOI18N
        lblMes.setForeground(new java.awt.Color(255, 255, 255));
        lblMes.setText("Mes :");
        pnlConsultaDeConsumo.add(lblMes);
        lblMes.setBounds(310, 27, 30, 30);

        lblAño.setFont(new java.awt.Font("Microsoft Tai Le", 2, 12)); // NOI18N
        lblAño.setForeground(new java.awt.Color(255, 255, 255));
        lblAño.setText("Año :");
        pnlConsultaDeConsumo.add(lblAño);
        lblAño.setBounds(470, 27, 40, 30);

        cmbAño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAñoActionPerformed(evt);
            }
        });
        pnlConsultaDeConsumo.add(cmbAño);
        cmbAño.setBounds(510, 30, 70, 30);

        jLabel3.setFont(new java.awt.Font("Yu Gothic Light", 0, 14)); // NOI18N
        jLabel3.setText("Ver");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlConsultaDeConsumo.add(jLabel3);
        jLabel3.setBounds(650, 30, 21, 23);

        jLabel4.setBackground(new java.awt.Color(0, 188, 212));
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel4.setOpaque(true);
        pnlConsultaDeConsumo.add(jLabel4);
        jLabel4.setBounds(620, 30, 80, 20);

        pnlParent.add(pnlConsultaDeConsumo, "card5");

        pnlSimuladorDeLlamada.setBackground(new java.awt.Color(51, 51, 51));
        pnlSimuladorDeLlamada.setLayout(null);

        lblDuracion.setFont(new java.awt.Font("Microsoft Tai Le", 2, 14)); // NOI18N
        lblDuracion.setForeground(new java.awt.Color(255, 255, 255));
        lblDuracion.setText("Duración:");
        pnlSimuladorDeLlamada.add(lblDuracion);
        lblDuracion.setBounds(80, 150, 60, 18);

        sdrDuracion.setBackground(new java.awt.Color(51, 51, 51));
        sdrDuracion.setMaximum(1000);
        sdrDuracion.setValue(500);
        pnlSimuladorDeLlamada.add(sdrDuracion);
        sdrDuracion.setBounds(150, 150, 190, 20);

        txtNumeroALlamar.setBackground(new java.awt.Color(51, 51, 51));
        txtNumeroALlamar.setFont(new java.awt.Font("Microsoft Tai Le", 2, 14)); // NOI18N
        txtNumeroALlamar.setForeground(new java.awt.Color(255, 255, 255));
        txtNumeroALlamar.setToolTipText("");
        pnlSimuladorDeLlamada.add(txtNumeroALlamar);
        txtNumeroALlamar.setBounds(80, 100, 320, 20);

        lblMin.setFont(new java.awt.Font("Microsoft Tai Le", 2, 14)); // NOI18N
        lblMin.setForeground(new java.awt.Color(255, 255, 255));
        lblMin.setText("Min : ");
        pnlSimuladorDeLlamada.add(lblMin);
        lblMin.setBounds(240, 268, 40, 30);

        lblMesSDL.setFont(new java.awt.Font("Microsoft Tai Le", 2, 14)); // NOI18N
        lblMesSDL.setForeground(new java.awt.Color(255, 255, 255));
        lblMesSDL.setText("Mes:");
        pnlSimuladorDeLlamada.add(lblMesSDL);
        lblMesSDL.setBounds(180, 210, 40, 30);

        lblAñoSDL.setFont(new java.awt.Font("Microsoft Tai Le", 2, 14)); // NOI18N
        lblAñoSDL.setForeground(new java.awt.Color(255, 255, 255));
        lblAñoSDL.setText("Año:");
        pnlSimuladorDeLlamada.add(lblAñoSDL);
        lblAñoSDL.setBounds(300, 210, 30, 30);

        cmbMesSDL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        pnlSimuladorDeLlamada.add(cmbMesSDL);
        cmbMesSDL.setBounds(220, 210, 60, 30);

        cmbDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado", "Domingo" }));
        pnlSimuladorDeLlamada.add(cmbDia);
        cmbDia.setBounds(110, 210, 60, 30);

        pnlSimuladorDeLlamada.add(cmdAñoSDL);
        cmdAñoSDL.setBounds(340, 210, 50, 30);

        lblBarraNumeroALlamar.setBackground(new java.awt.Color(153, 153, 153));
        lblBarraNumeroALlamar.setOpaque(true);
        pnlSimuladorDeLlamada.add(lblBarraNumeroALlamar);
        lblBarraNumeroALlamar.setBounds(80, 120, 250, 1);

        lblDia.setFont(new java.awt.Font("Microsoft Tai Le", 2, 14)); // NOI18N
        lblDia.setForeground(new java.awt.Color(255, 255, 255));
        lblDia.setText("Dia:");
        pnlSimuladorDeLlamada.add(lblDia);
        lblDia.setBounds(80, 210, 30, 30);

        cmbHora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        pnlSimuladorDeLlamada.add(cmbHora);
        cmbHora.setBounds(180, 270, 40, 30);

        lblHora.setFont(new java.awt.Font("Microsoft Tai Le", 2, 14)); // NOI18N
        lblHora.setForeground(new java.awt.Color(255, 255, 255));
        lblHora.setText("Hora :");
        pnlSimuladorDeLlamada.add(lblHora);
        lblHora.setBounds(130, 270, 40, 30);

        cmbMin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        pnlSimuladorDeLlamada.add(cmbMin);
        cmbMin.setBounds(280, 270, 40, 30);

        lblAceptarSDL.setFont(new java.awt.Font("Yu Gothic", 2, 14)); // NOI18N
        lblAceptarSDL.setText("Aceptar");
        lblAceptarSDL.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlSimuladorDeLlamada.add(lblAceptarSDL);
        lblAceptarSDL.setBounds(200, 320, 60, 23);

        lblFondoAceptarSDL.setBackground(new java.awt.Color(0, 188, 212));
        lblFondoAceptarSDL.setAutoscrolls(true);
        lblFondoAceptarSDL.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblFondoAceptarSDL.setOpaque(true);
        pnlSimuladorDeLlamada.add(lblFondoAceptarSDL);
        lblFondoAceptarSDL.setBounds(140, 320, 180, 20);

        lblAutoGenerarLlamada.setFont(new java.awt.Font("Yu Gothic", 2, 14)); // NOI18N
        lblAutoGenerarLlamada.setText("Auto-generar llamada");
        lblAutoGenerarLlamada.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlSimuladorDeLlamada.add(lblAutoGenerarLlamada);
        lblAutoGenerarLlamada.setBounds(160, 380, 142, 20);

        lblFondoAutoGenerarLlamada.setBackground(new java.awt.Color(0, 188, 212));
        lblFondoAutoGenerarLlamada.setAutoscrolls(true);
        lblFondoAutoGenerarLlamada.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblFondoAutoGenerarLlamada.setOpaque(true);
        pnlSimuladorDeLlamada.add(lblFondoAutoGenerarLlamada);
        lblFondoAutoGenerarLlamada.setBounds(110, 380, 240, 20);

        lbl1.setFont(new java.awt.Font("Wide Latin", 1, 18)); // NOI18N
        lbl1.setForeground(new java.awt.Color(255, 255, 255));
        lbl1.setText("1");
        lbl1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlSimuladorDeLlamada.add(lbl1);
        lbl1.setBounds(500, 139, 20, 30);

        lbl2.setFont(new java.awt.Font("Wide Latin", 1, 18)); // NOI18N
        lbl2.setForeground(new java.awt.Color(255, 255, 255));
        lbl2.setText("2");
        lbl2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlSimuladorDeLlamada.add(lbl2);
        lbl2.setBounds(560, 139, 30, 30);

        lbl3.setFont(new java.awt.Font("Wide Latin", 1, 18)); // NOI18N
        lbl3.setForeground(new java.awt.Color(255, 255, 255));
        lbl3.setText("3");
        lbl3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlSimuladorDeLlamada.add(lbl3);
        lbl3.setBounds(620, 140, 30, 30);

        lbl4.setFont(new java.awt.Font("Wide Latin", 1, 18)); // NOI18N
        lbl4.setForeground(new java.awt.Color(255, 255, 255));
        lbl4.setText("4");
        lbl4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlSimuladorDeLlamada.add(lbl4);
        lbl4.setBounds(500, 189, 30, 30);

        lbl5.setFont(new java.awt.Font("Wide Latin", 1, 18)); // NOI18N
        lbl5.setForeground(new java.awt.Color(255, 255, 255));
        lbl5.setText("5");
        lbl5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlSimuladorDeLlamada.add(lbl5);
        lbl5.setBounds(559, 189, 21, 30);

        lbl6.setFont(new java.awt.Font("Wide Latin", 1, 18)); // NOI18N
        lbl6.setForeground(new java.awt.Color(255, 255, 255));
        lbl6.setText("6");
        lbl6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlSimuladorDeLlamada.add(lbl6);
        lbl6.setBounds(620, 190, 30, 30);

        lbl7.setFont(new java.awt.Font("Wide Latin", 1, 18)); // NOI18N
        lbl7.setForeground(new java.awt.Color(255, 255, 255));
        lbl7.setText("7");
        lbl7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlSimuladorDeLlamada.add(lbl7);
        lbl7.setBounds(500, 239, 20, 30);

        lbl8.setFont(new java.awt.Font("Wide Latin", 1, 18)); // NOI18N
        lbl8.setForeground(new java.awt.Color(255, 255, 255));
        lbl8.setText("8");
        lbl8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlSimuladorDeLlamada.add(lbl8);
        lbl8.setBounds(560, 240, 30, 30);

        lbl9.setFont(new java.awt.Font("Wide Latin", 1, 18)); // NOI18N
        lbl9.setForeground(new java.awt.Color(255, 255, 255));
        lbl9.setText("9");
        lbl9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlSimuladorDeLlamada.add(lbl9);
        lbl9.setBounds(617, 239, 23, 30);

        lbl0.setFont(new java.awt.Font("Wide Latin", 1, 18)); // NOI18N
        lbl0.setForeground(new java.awt.Color(255, 255, 255));
        lbl0.setText("0");
        lbl0.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlSimuladorDeLlamada.add(lbl0);
        lbl0.setBounds(560, 289, 30, 30);

        lblFondo2.setBackground(new java.awt.Color(0, 121, 107));
        lblFondo2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblFondo2.setOpaque(true);
        pnlSimuladorDeLlamada.add(lblFondo2);
        lblFondo2.setBounds(550, 140, 40, 30);

        lblFondo3.setBackground(new java.awt.Color(0, 121, 107));
        lblFondo3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblFondo3.setOpaque(true);
        pnlSimuladorDeLlamada.add(lblFondo3);
        lblFondo3.setBounds(610, 140, 40, 30);

        lblFondo4.setBackground(new java.awt.Color(0, 121, 107));
        lblFondo4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblFondo4.setOpaque(true);
        pnlSimuladorDeLlamada.add(lblFondo4);
        lblFondo4.setBounds(490, 190, 40, 30);

        lblFondo5.setBackground(new java.awt.Color(0, 121, 107));
        lblFondo5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblFondo5.setOpaque(true);
        pnlSimuladorDeLlamada.add(lblFondo5);
        lblFondo5.setBounds(550, 190, 40, 30);

        lblFondo6.setBackground(new java.awt.Color(0, 121, 107));
        lblFondo6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblFondo6.setOpaque(true);
        pnlSimuladorDeLlamada.add(lblFondo6);
        lblFondo6.setBounds(610, 190, 40, 30);

        lblFondo7.setBackground(new java.awt.Color(0, 121, 107));
        lblFondo7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblFondo7.setOpaque(true);
        pnlSimuladorDeLlamada.add(lblFondo7);
        lblFondo7.setBounds(490, 240, 40, 30);

        lblFondo8.setBackground(new java.awt.Color(0, 121, 107));
        lblFondo8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblFondo8.setOpaque(true);
        pnlSimuladorDeLlamada.add(lblFondo8);
        lblFondo8.setBounds(550, 240, 40, 30);

        lblFondo9.setBackground(new java.awt.Color(0, 121, 107));
        lblFondo9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblFondo9.setOpaque(true);
        pnlSimuladorDeLlamada.add(lblFondo9);
        lblFondo9.setBounds(610, 240, 40, 30);

        lblFondo0.setBackground(new java.awt.Color(0, 121, 107));
        lblFondo0.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblFondo0.setOpaque(true);
        pnlSimuladorDeLlamada.add(lblFondo0);
        lblFondo0.setBounds(550, 290, 40, 30);

        lblFondo1.setBackground(new java.awt.Color(0, 121, 107));
        lblFondo1.setOpaque(true);
        pnlSimuladorDeLlamada.add(lblFondo1);
        lblFondo1.setBounds(490, 140, 40, 30);

        lblNoLlamarOculto.setFont(new java.awt.Font("Microsoft Tai Le", 2, 16)); // NOI18N
        lblNoLlamarOculto.setForeground(new java.awt.Color(255, 255, 255));
        lblNoLlamarOculto.setText("Número a llamar :");
        pnlSimuladorDeLlamada.add(lblNoLlamarOculto);
        lblNoLlamarOculto.setBounds(80, 80, 160, 21);

        lblNoCuentaOculto.setFont(new java.awt.Font("Microsoft Tai Le", 2, 16)); // NOI18N
        lblNoCuentaOculto.setForeground(new java.awt.Color(255, 255, 255));
        lblNoCuentaOculto.setText("Cliente :");
        pnlSimuladorDeLlamada.add(lblNoCuentaOculto);
        lblNoCuentaOculto.setBounds(80, 10, 170, 21);

        lblBarraNumeroALlamar1.setBackground(new java.awt.Color(153, 153, 153));
        lblBarraNumeroALlamar1.setOpaque(true);
        pnlSimuladorDeLlamada.add(lblBarraNumeroALlamar1);
        lblBarraNumeroALlamar1.setBounds(90, 60, 250, 0);

        pnlSimuladorDeLlamada.add(jComboBox1);
        jComboBox1.setBounds(80, 30, 250, 30);

        lblCuenta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCuenta.setForeground(new java.awt.Color(255, 255, 255));
        pnlSimuladorDeLlamada.add(lblCuenta);
        lblCuenta.setBounds(400, 30, 300, 30);

        pnlParent.add(pnlSimuladorDeLlamada, "card2");

        getContentPane().add(pnlParent);
        pnlParent.setBounds(290, 0, 730, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
     
            

    }//GEN-LAST:event_formMouseClicked

    private void lblFondoConsultaDeConsumoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFondoConsultaDeConsumoMouseMoved
     
        lblFondoConsultaDeConsumo.setCursor(new Cursor (Cursor.HAND_CURSOR));
        lblIconoConsultaDeConsumo.setCursor(new Cursor (Cursor.HAND_CURSOR));
        lblConsultaDeConsumo.setCursor(new Cursor (Cursor.HAND_CURSOR));
        lblFondoConsultaDeConsumo.setBackground(new Color (66,66,66));	
        lblFondoListaDeClientes.setBackground(new Color (33,33,33));	
        lblFondoAgregarCliente.setBackground(new Color (33,33,33));
        lblFondoSimuladorDeLlamada.setBackground(new Color (33,33,33));
       this.repaint();
       this.revalidate();
       
    }//GEN-LAST:event_lblFondoConsultaDeConsumoMouseMoved

    private void lblFondoSimuladorDeLlamadaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFondoSimuladorDeLlamadaMouseMoved
        lblFondoSimuladorDeLlamada.setCursor(new Cursor (Cursor.HAND_CURSOR));
         lblIconoSimuladorDeLlamada.setCursor(new Cursor (Cursor.HAND_CURSOR));
        lblSimuladorDeLlamada.setCursor(new Cursor (Cursor.HAND_CURSOR));
        lblFondoSimuladorDeLlamada.setBackground(new Color (66,66,66));
        lblFondoListaDeClientes.setBackground(new Color (33,33,33));	
        lblFondoConsultaDeConsumo.setBackground(new Color (33,33,33));
        lblFondoAgregarCliente.setBackground(new Color (33,33,33));
         this.repaint();
       this.revalidate();
    }//GEN-LAST:event_lblFondoSimuladorDeLlamadaMouseMoved

    private void pnlParentMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlParentMouseMoved
         lblFondoSimuladorDeLlamada.setBackground(new Color (33,33,33));	
        lblFondoConsultaDeConsumo.setBackground(new Color (33,33,33));
        lblFondoAgregarCliente.setBackground(new Color (33,33,33));  
                lblFondoListaDeClientes.setBackground(new Color (33,33,33));		
   this.repaint();
       this.revalidate();
    }//GEN-LAST:event_pnlParentMouseMoved

    private void lblFondoListaDeClientesMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFondoListaDeClientesMouseMoved
        lblFondoListaDeClientes.setCursor(new Cursor (Cursor.HAND_CURSOR));
        lblIconoListaDeClientes.setCursor(new Cursor (Cursor.HAND_CURSOR));
        lblListaDeClientes.setCursor(new Cursor (Cursor.HAND_CURSOR));
        lblFondoListaDeClientes.setBackground(new Color (66,66,66));
        lblFondoSimuladorDeLlamada.setBackground(new Color (33,33,33));	
        lblFondoConsultaDeConsumo.setBackground(new Color (33,33,33));
        lblFondoAgregarCliente.setBackground(new Color (33,33,33));
         this.repaint();
       this.revalidate();
    }//GEN-LAST:event_lblFondoListaDeClientesMouseMoved

    private void lblFondoAgregarClienteMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFondoAgregarClienteMouseMoved
         lblFondoAgregarCliente.setCursor(new Cursor (Cursor.HAND_CURSOR));
         lblIconoAgregarCliente.setCursor(new Cursor (Cursor.HAND_CURSOR));
        lblAgregarCliente.setCursor(new Cursor (Cursor.HAND_CURSOR));
        lblFondoAgregarCliente.setBackground(new Color (66,66,66));
        lblFondoListaDeClientes.setBackground(new Color (33,33,33));	
        lblFondoConsultaDeConsumo.setBackground(new Color (33,33,33));
        lblFondoSimuladorDeLlamada.setBackground(new Color (33,33,33));
         this.repaint();
       this.revalidate();
    }//GEN-LAST:event_lblFondoAgregarClienteMouseMoved

    private void lblFondoIzquierdoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFondoIzquierdoMouseMoved
   lblFondoSimuladorDeLlamada.setBackground(new Color (33,33,33));	
        lblFondoConsultaDeConsumo.setBackground(new Color (33,33,33));
        lblFondoAgregarCliente.setBackground(new Color (33,33,33));  
                lblFondoListaDeClientes.setBackground(new Color (33,33,33));	
   this.repaint();
       this.revalidate();
    }//GEN-LAST:event_lblFondoIzquierdoMouseMoved

    private void lblFondoListaDeClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFondoListaDeClientesMouseClicked

    pnlParent.removeAll();
    pnlParent.add(pnlListaDeClientes);
    pnlParent.repaint();
    pnlParent.revalidate();
        
    }//GEN-LAST:event_lblFondoListaDeClientesMouseClicked

    private void lblFondoAgregarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFondoAgregarClienteMouseClicked
    pnlParent.removeAll();
    pnlParent.add(pnlAgregarCliente);
    pnlParent.repaint();
    pnlParent.revalidate();
        
    }//GEN-LAST:event_lblFondoAgregarClienteMouseClicked

    private void lblFondoConsultaDeConsumoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFondoConsultaDeConsumoMouseClicked
    pnlParent.removeAll();
    pnlParent.add(pnlConsultaDeConsumo);
    pnlParent.repaint();    
    pnlParent.revalidate();
    }//GEN-LAST:event_lblFondoConsultaDeConsumoMouseClicked

    private void lblFondoSimuladorDeLlamadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFondoSimuladorDeLlamadaMouseClicked
    
    pnlParent.removeAll();
    pnlParent.add(pnlSimuladorDeLlamada);
    pnlParent.repaint();
    pnlParent.revalidate();

    }//GEN-LAST:event_lblFondoSimuladorDeLlamadaMouseClicked

    private void lblAgregarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAgregarClienteMouseClicked
    pnlParent.removeAll();
    pnlParent.add(pnlAgregarCliente);
    pnlParent.repaint();
    pnlParent.revalidate();
    }//GEN-LAST:event_lblAgregarClienteMouseClicked

    private void lblIconoAgregarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconoAgregarClienteMouseClicked
    pnlParent.removeAll();
    pnlParent.add(pnlAgregarCliente);
    pnlParent.repaint();
    pnlParent.revalidate();
    }//GEN-LAST:event_lblIconoAgregarClienteMouseClicked

    private void lblListaDeClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblListaDeClientesMouseClicked
    pnlParent.removeAll();
    pnlParent.add(pnlListaDeClientes);
    pnlParent.repaint();
    pnlParent.revalidate();
    }//GEN-LAST:event_lblListaDeClientesMouseClicked

    private void lblIconoListaDeClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconoListaDeClientesMouseClicked
    pnlParent.removeAll();
    pnlParent.add(pnlListaDeClientes);
    pnlParent.repaint();
    pnlParent.revalidate();
    }//GEN-LAST:event_lblIconoListaDeClientesMouseClicked

    private void lblConsultaDeConsumoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConsultaDeConsumoMouseClicked
    pnlParent.removeAll();
    pnlParent.add(pnlConsultaDeConsumo);
    pnlParent.repaint();    
    pnlParent.revalidate();
    }//GEN-LAST:event_lblConsultaDeConsumoMouseClicked

    private void lblIconoConsultaDeConsumoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconoConsultaDeConsumoMouseClicked
    pnlParent.removeAll();
    pnlParent.add(pnlConsultaDeConsumo);
    pnlParent.repaint();    
    pnlParent.revalidate();
    }//GEN-LAST:event_lblIconoConsultaDeConsumoMouseClicked

    private void lblSimuladorDeLlamadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSimuladorDeLlamadaMouseClicked
    pnlParent.removeAll();
    pnlParent.add(pnlSimuladorDeLlamada);
    pnlParent.repaint();
    pnlParent.revalidate();
    }//GEN-LAST:event_lblSimuladorDeLlamadaMouseClicked

    private void lblIconoSimuladorDeLlamadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconoSimuladorDeLlamadaMouseClicked
    pnlParent.removeAll();
    pnlParent.add(pnlSimuladorDeLlamada);
    pnlParent.repaint();
    pnlParent.revalidate();
    }//GEN-LAST:event_lblIconoSimuladorDeLlamadaMouseClicked

    private void cmbMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMesActionPerformed

    private void cmbAñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAñoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbAñoActionPerformed

    private void lblFondoAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFondoAceptarMouseClicked
         Random rng = new Random();
       int ran = rng.nextInt(90000000)+10000000; 
       opu.Agregar(ran, txtNombre.getText(), txtApellidos.getText(), txtDireccion.getText(), cmbEstado.getSelectedItem().toString(), cmbCiudad.getSelectedItem().toString(), txtTelefono.getText());
       txtNombre.setText(null);
       txtApellidos.setText(null);
       txtDireccion.setText(null);
       txtTelefono.setText(null);
    }//GEN-LAST:event_lblFondoAceptarMouseClicked

    private void cmbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEstadoActionPerformed
    cmbCiudad.removeAllItems();
    BufferedReader abc = null;
    String xdd = cmbEstado.getSelectedItem().toString()+".txt";
        try {
            abc = new BufferedReader(new FileReader("src/mx/itson/tekz/persistencia/"+xdd));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(mainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }

    String Linea;
    String ciudad = "";
    ArrayList<String> Municipios = new ArrayList<String>(); 
    DefaultComboBoxModel modelc = (DefaultComboBoxModel) cmbCiudad.getModel();
    try {
            while((Linea = abc.readLine()) != null) {
                String [] xd =Linea.split("\\s+");
                        
                if (xd.length > 1) {
                    for (int i = 1; i < xd.length; i++) {
                        ciudad += xd[i]+" ";
                    }
                }
                 
                
                //Municipios.add(xd[1]);
                modelc.addElement(ciudad);
                ciudad="";
              //  System.out.println(line);
            }       } catch (IOException ex) {
            Logger.getLogger(mainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_cmbEstadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainMenu().setVisible(true);
            }
        });
        
    }
    
   public void Cargar(){
    tblClientes.getTableHeader().setFont(new Font("Microsoft Tai Le", Font.ITALIC, 14));
    tblClientes.getTableHeader().setForeground(Color.WHITE);
    tblClientes.getTableHeader().setBackground(Color.yellow);
    tblClientes.getTableHeader().setOpaque(false);
    tblClientes.setShowGrid(false);
    tblClientes.setOpaque(false);
   ((DefaultTableCellRenderer)tblClientes.getDefaultRenderer(Object.class)).setOpaque(false);
    jScrollPane1.setOpaque(false);
    jScrollPane1.getViewport().setOpaque(false);
    
    BufferedReader abc = null;
    String xdd = "Aguascalientes.txt";
        try {
            abc = new BufferedReader(new FileReader("src/mx/itson/tekz/persistencia/"+xdd));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(mainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }

    String Linea;
    String ciudad = "";
    ArrayList<String> Municipios = new ArrayList<String>(); 
    DefaultComboBoxModel modelc = (DefaultComboBoxModel) cmbCiudad.getModel();
    try {
            while((Linea = abc.readLine()) != null) {
                String [] xd =Linea.split("\\s+");
                        
                if (xd.length > 1) {
                    for (int i = 1; i < xd.length; i++) {
                        ciudad += xd[i]+" ";
                    }
                }
                 
                
                Municipios.add(xd[1]);
                modelc.addElement(ciudad);
                ciudad="";
              //  System.out.println(line);
            }       } catch (IOException ex) {
            Logger.getLogger(mainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbAño;
    private javax.swing.JComboBox<String> cmbCiudad;
    private javax.swing.JComboBox<String> cmbDia;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JComboBox<String> cmbHora;
    private javax.swing.JComboBox<String> cmbMes;
    private javax.swing.JComboBox<String> cmbMesSDL;
    private javax.swing.JComboBox<String> cmbMin;
    private javax.swing.JComboBox<String> cmdAñoSDL;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl0;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel lbl7;
    private javax.swing.JLabel lbl8;
    private javax.swing.JLabel lbl9;
    private javax.swing.JLabel lblAceptar;
    private javax.swing.JLabel lblAceptarSDL;
    private javax.swing.JLabel lblAgregarCliente;
    private static javax.swing.JLabel lblApellidosOculto;
    private javax.swing.JLabel lblAutoGenerarLlamada;
    private javax.swing.JLabel lblAño;
    private javax.swing.JLabel lblAñoSDL;
    private javax.swing.JLabel lblBarraApellidos;
    private javax.swing.JLabel lblBarraNombre;
    private javax.swing.JLabel lblBarraNumeroALlamar;
    private javax.swing.JLabel lblBarraNumeroALlamar1;
    private javax.swing.JLabel lblBarraNumeroDeCuenta;
    private javax.swing.JLabel lblCiudad;
    private javax.swing.JLabel lblConsultaDeConsumo;
    private javax.swing.JLabel lblCuenta;
    private javax.swing.JLabel lblDia;
    private static javax.swing.JLabel lblDireccionOculto;
    private javax.swing.JLabel lblDuracion;
    private javax.swing.JLabel lblEditar;
    private javax.swing.JLabel lblEliminar;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFondo0;
    private javax.swing.JLabel lblFondo1;
    private javax.swing.JLabel lblFondo2;
    private javax.swing.JLabel lblFondo3;
    private javax.swing.JLabel lblFondo4;
    private javax.swing.JLabel lblFondo5;
    private javax.swing.JLabel lblFondo6;
    private javax.swing.JLabel lblFondo7;
    private javax.swing.JLabel lblFondo8;
    private javax.swing.JLabel lblFondo9;
    private javax.swing.JLabel lblFondoAceptar;
    private javax.swing.JLabel lblFondoAceptarSDL;
    private javax.swing.JLabel lblFondoAgregarCliente;
    private javax.swing.JLabel lblFondoAutoGenerarLlamada;
    private javax.swing.JLabel lblFondoConsultaDeConsumo;
    private javax.swing.JLabel lblFondoEditar;
    private javax.swing.JLabel lblFondoEliminar;
    private javax.swing.JLabel lblFondoIzquierdo;
    private javax.swing.JLabel lblFondoListaDeClientes;
    private javax.swing.JLabel lblFondoSimuladorDeLlamada;
    private javax.swing.JLabel lblFondoVerCliente;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblIconoAgregarCliente;
    private javax.swing.JLabel lblIconoConsultaDeConsumo;
    private javax.swing.JLabel lblIconoListaDeClientes;
    private javax.swing.JLabel lblIconoSimuladorDeLlamada;
    private javax.swing.JLabel lblListaDeClientes;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMes;
    private javax.swing.JLabel lblMesSDL;
    private javax.swing.JLabel lblMin;
    private javax.swing.JLabel lblNoCuentaOculto;
    private javax.swing.JLabel lblNoLlamarOculto;
    private static javax.swing.JLabel lblNombreOculto;
    private javax.swing.JLabel lblSimuladorDeLlamada;
    private javax.swing.JLabel lblTelefono;
    private static javax.swing.JLabel lblTelefonoOculto;
    private javax.swing.JLabel lblVerCliente;
    private javax.swing.JPanel pnlAgregarCliente;
    private javax.swing.JPanel pnlConsultaDeConsumo;
    private javax.swing.JPanel pnlListaDeClientes;
    private javax.swing.JPanel pnlParent;
    private javax.swing.JPanel pnlSimuladorDeLlamada;
    private javax.swing.JSlider sdrDuracion;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JLabel txtBarraDireccion;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumeroALlamar;
    private javax.swing.JTextField txtNumeroDeCuenta;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
